"usee client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppDataProvider } from "@/context/ApplicationContext";
import NavBar from "@/components/Navbar/NavBar";
import { useEffect, useMemo } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rent-Track",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authuser = useMemo(() => {
    if (typeof window == "undefined") {
      return null;
    }
    const t = localStorage.getItem("__user__");
    if (t && t != undefined) {
      return JSON.parse(t);
    } else {
      return null;
    }
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppDataProvider auth={authuser}>
          <NavBar />
          {children}
        </AppDataProvider>
      </body>
    </html>
  );
}
